// <auto-generated />
using System;
using MaximumGameStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaximumGameStore.Migrations
{
    [DbContext(typeof(MaximumGameStoreContext))]
    partial class MaximumGameStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaximumGameStore.Models.CardPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("CardLast4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("char(4)")
                        .IsFixedLength();

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DateTimePayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__CardPaym__3214EC27478CC0A3");

                    b.HasIndex(new[] { "OrderId" }, "UQ__CardPaym__C3905BAE08388269")
                        .IsUnique();

                    b.ToTable("CardPayments");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("DateTimeUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__Cart__3214EC279A7183F5");

                    b.HasIndex("UserId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("MaximumGameStore.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("CartID");

                    b.Property<DateTime>("DateTimeAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.HasKey("Id")
                        .HasName("PK__CartItem__3214EC275DC5A9A0");

                    b.HasIndex("GameId");

                    b.HasIndex(new[] { "CartId", "GameId" }, "UQ_Cart_Game")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Develope__3214EC27C9564D31");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Engines__3214EC27953C4571");

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("int")
                        .HasColumnName("SeriesID");

                    b.HasKey("Id")
                        .HasName("PK__Games__3214EC2764629950");

                    b.HasIndex("SeriesId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MaximumGameStore.Models.GameDeveloper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int")
                        .HasColumnName("DeveloperID");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.HasKey("Id")
                        .HasName("PK__GameDeve__3214EC27C27F4E79");

                    b.HasIndex("DeveloperId");

                    b.HasIndex(new[] { "GameId", "DeveloperId" }, "UQ_GameDeveloper")
                        .IsUnique();

                    b.ToTable("GameDevelopers");
                });

            modelBuilder.Entity("MaximumGameStore.Models.GameEngine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EngineId")
                        .HasColumnType("int")
                        .HasColumnName("EngineID");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.HasKey("Id")
                        .HasName("PK__GameEngi__3214EC27407B4504");

                    b.HasIndex("EngineId");

                    b.HasIndex(new[] { "GameId", "EngineId" }, "UQ_GameEngines")
                        .IsUnique();

                    b.ToTable("GameEngines");
                });

            modelBuilder.Entity("MaximumGameStore.Models.GameGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("GenreID");

                    b.HasKey("Id")
                        .HasName("PK__GameGenr__3214EC27CEA12E99");

                    b.HasIndex("GenreId");

                    b.HasIndex(new[] { "GameId", "GenreId" }, "UQ_GameGenres")
                        .IsUnique();

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("MaximumGameStore.Models.GameImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__GameImag__3214EC27DCF1C389");

                    b.HasIndex("GameId");

                    b.ToTable("GameImages");
                });

            modelBuilder.Entity("MaximumGameStore.Models.GameMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int>("ModeId")
                        .HasColumnType("int")
                        .HasColumnName("ModeID");

                    b.HasKey("Id")
                        .HasName("PK__GameMode__3214EC270A27860E");

                    b.HasIndex("ModeId");

                    b.HasIndex(new[] { "GameId", "ModeId" }, "UQ_GameModes")
                        .IsUnique();

                    b.ToTable("GameModes");
                });

            modelBuilder.Entity("MaximumGameStore.Models.GamePublisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int")
                        .HasColumnName("PublisherID");

                    b.HasKey("Id")
                        .HasName("PK__GamePubl__3214EC27F14ACB93");

                    b.HasIndex("PublisherId");

                    b.HasIndex(new[] { "GameId", "PublisherId" }, "UQ_GamePublishers")
                        .IsUnique();

                    b.ToTable("GamePublishers");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__Genres__3214EC27CF0BEA60");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Mode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Modes__3214EC2792ED1690");

                    b.ToTable("Modes");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC27F26E5434");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MaximumGameStore.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__OrderIte__3214EC2701EDAA42");

                    b.HasIndex("GameId");

                    b.HasIndex(new[] { "OrderId", "GameId" }, "UQ_Order_Game")
                        .IsUnique();

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Publishe__3214EC27034F18A8");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Series__3214EC27289A20FA");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("MaximumGameStore.Models.SystemRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("CPU");

                    b.Property<string>("DirectX")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<string>("Gpu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("GPU");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("OS");

                    b.Property<int>("RamGb")
                        .HasColumnType("int")
                        .HasColumnName("RAM_GB");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StorageGb")
                        .HasColumnType("int")
                        .HasColumnName("Storage_GB");

                    b.HasKey("Id")
                        .HasName("PK__SystemRe__3214EC27D8C6B86D");

                    b.HasIndex(new[] { "GameId", "RequirementType" }, "UQ_RequirementType_Game")
                        .IsUnique();

                    b.ToTable("SystemRequirements");
                });

            modelBuilder.Entity("MaximumGameStore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeRegistration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("User");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC275525C94A");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105346F83D4F9")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MaximumGameStore.Models.CardPayment", b =>
                {
                    b.HasOne("MaximumGameStore.Models.Order", "Order")
                        .WithOne("CardPayment")
                        .HasForeignKey("MaximumGameStore.Models.CardPayment", "OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_CardPayments_Orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Cart", b =>
                {
                    b.HasOne("MaximumGameStore.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Cart_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MaximumGameStore.Models.CartItem", b =>
                {
                    b.HasOne("MaximumGameStore.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Cart");

                    b.HasOne("MaximumGameStore.Models.Game", "Game")
                        .WithMany("CartItems")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Games");

                    b.Navigation("Cart");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Game", b =>
                {
                    b.HasOne("MaximumGameStore.Models.Series", "Series")
                        .WithMany("Games")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Games_Series");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MaximumGameStore.Models.GameDeveloper", b =>
                {
                    b.HasOne("MaximumGameStore.Models.Developer", "Developer")
                        .WithMany("GameDevelopers")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GameDevelopers_Developers");

                    b.HasOne("MaximumGameStore.Models.Game", "Game")
                        .WithMany("GameDevelopers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GameDevelopers_Games");

                    b.Navigation("Developer");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MaximumGameStore.Models.GameEngine", b =>
                {
                    b.HasOne("MaximumGameStore.Models.Engine", "Engine")
                        .WithMany("GameEngines")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GameEngines_Engines");

                    b.HasOne("MaximumGameStore.Models.Game", "Game")
                        .WithMany("GameEngines")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GameEngines_Games");

                    b.Navigation("Engine");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MaximumGameStore.Models.GameGenre", b =>
                {
                    b.HasOne("MaximumGameStore.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GameGenres_Games");

                    b.HasOne("MaximumGameStore.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GameGenres_Genres");

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MaximumGameStore.Models.GameImage", b =>
                {
                    b.HasOne("MaximumGameStore.Models.Game", "Game")
                        .WithMany("GameImages")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GameImages_Games");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MaximumGameStore.Models.GameMode", b =>
                {
                    b.HasOne("MaximumGameStore.Models.Game", "Game")
                        .WithMany("GameModes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GameModes_Games");

                    b.HasOne("MaximumGameStore.Models.Mode", "Mode")
                        .WithMany("GameModes")
                        .HasForeignKey("ModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GameModes_Modes");

                    b.Navigation("Game");

                    b.Navigation("Mode");
                });

            modelBuilder.Entity("MaximumGameStore.Models.GamePublisher", b =>
                {
                    b.HasOne("MaximumGameStore.Models.Game", "Game")
                        .WithMany("GamePublishers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GamePublishers_Games");

                    b.HasOne("MaximumGameStore.Models.Publisher", "Publisher")
                        .WithMany("GamePublishers")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GamePublishers_Publishers");

                    b.Navigation("Game");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Order", b =>
                {
                    b.HasOne("MaximumGameStore.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MaximumGameStore.Models.OrderItem", b =>
                {
                    b.HasOne("MaximumGameStore.Models.Game", "Game")
                        .WithMany("OrderItems")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderItems_Games");

                    b.HasOne("MaximumGameStore.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderItems_Orders");

                    b.Navigation("Game");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MaximumGameStore.Models.SystemRequirement", b =>
                {
                    b.HasOne("MaximumGameStore.Models.Game", "Game")
                        .WithMany("SystemRequirements")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SystemRequirements_Games");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Developer", b =>
                {
                    b.Navigation("GameDevelopers");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Engine", b =>
                {
                    b.Navigation("GameEngines");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Game", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("GameDevelopers");

                    b.Navigation("GameEngines");

                    b.Navigation("GameGenres");

                    b.Navigation("GameImages");

                    b.Navigation("GameModes");

                    b.Navigation("GamePublishers");

                    b.Navigation("OrderItems");

                    b.Navigation("SystemRequirements");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Mode", b =>
                {
                    b.Navigation("GameModes");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Order", b =>
                {
                    b.Navigation("CardPayment");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Publisher", b =>
                {
                    b.Navigation("GamePublishers");
                });

            modelBuilder.Entity("MaximumGameStore.Models.Series", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("MaximumGameStore.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
